models:
    ollama_model_names: model or [model1, model2, ...]                  # List (or single string) of model identifiers as recognized by Ollama (see: https://ollama.com/library)
    output_names: model_name or [model_name1, model_name2, ...]         # List (or single string) of custom names of models used in output filenames (<person_name>_LLM_data_<output_name>_prompt_<prompt_id>.json)

dataset_path: ...                 # Path to the dataset directory
output_path: ...                  # Path to the output directory

save_stats: ...                   # True/False to enable saving time statistics (e.g., model load time, annotation time)

