models:
    ollama_model_names: [llama3.3, deepseek-r1:70b, deepseek-r1:32b, deepseek-r1:14b, deepseek-r1:8b, deepseek-r1:7b]
    output_names: [llama3-3-70B, deepseek-r1-llama-70B, deepseek-r1-qwen-32B, deepseek-r1-qwen-14B, deepseek-r1-llama-8B, deepseek-r1-qwen-7B]

dataset_path: "./datasets/example_set" 
output_path: "./outputs/example_set"

save_stats: TRUE


    


